# Generated by Django 4.2.7 on 2026-03-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=200)),
                ('diocese', models.CharField(blank=True, max_length=200)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('church_logo', models.ImageField(blank=True, null=True, upload_to='assets/images/church/', verbose_name='Church Logo')),
                ('prime_bishop_name', models.CharField(blank=True, max_length=200, verbose_name='Prime Bishop Name')),
                ('prime_bishop_details', models.TextField(blank=True, verbose_name='Prime Bishop Details')),
                ('prime_bishop_image', models.ImageField(blank=True, null=True, upload_to='assets/images/priests/', verbose_name='Prime Bishop Image')),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True)),
            ],
            options={
                'verbose_name': 'Parish Info',
            },
        ),
        
        # Create Church model first
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Church Name')),
                ('location', models.CharField(help_text='Full address of the church', max_length=300, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bishop', models.CharField(blank=True, help_text='Current bishop of the church', max_length=200, verbose_name='Bishop')),
                ('prime_bishop_name', models.CharField(blank=True, max_length=200, verbose_name='Prime Bishop Name')),
                ('prime_bishop_image', models.ImageField(blank=True, null=True, upload_to='assets/images/priests/', verbose_name='Prime Bishop Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/church/', verbose_name='Church Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'ordering': ['name'],
            },
        ),
        
        # Create Parish model (depends on Church)
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Parish Name')),
                ('parish_type', models.CharField(choices=[('cathedral', 'Cathedral'), ('parish', 'Parish'), ('mission', 'Mission'), ('chapel', 'Chapel')], default='parish', max_length=20, verbose_name='Parish Type')),
                ('location', models.CharField(help_text='Full address of the parish', max_length=300, verbose_name='Location')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date Updated')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='registry.church', verbose_name='Church')),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'ordering': ['name'],
            },
        ),
        
        # Create Member model (depends on Church and Parish)
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('church', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='members', 
                    to='registry.church', 
                    verbose_name='Assigned Church/Diocese'
                )),
                ('parish', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='members', 
                    to='registry.parish', 
                    verbose_name='Assigned Parish'
                )),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        
        # Create other models that don't depend on Church/Parish or only depend on Member
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('meeting_schedule', models.CharField(blank=True, max_length=200, verbose_name='Meeting Schedule')),
                ('meeting_venue', models.CharField(blank=True, max_length=200, verbose_name='Meeting Venue')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact Person')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        
        migrations.CreateModel(
            name='Baptism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_baptized', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('godfathers', models.TextField(blank=True, default='', help_text='Comma-separated list of godfathers')),
                ('godmothers', models.TextField(blank=True, default='', help_text='Comma-separated list of godmothers')),
                ('birth_certificate_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baptism', to='registry.member')),
            ],
        ),
        
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmed', models.DateField()),
                ('bishop', models.CharField(max_length=150)),
                ('confirmation_name', models.CharField(max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='registry.member')),
            ],
        ),
        
        migrations.CreateModel(
            name='FirstHolyCommunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communion', to='registry.member')),
            ],
        ),
        
        migrations.CreateModel(
            name='LastRites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_rites', to='registry.member')),
            ],
        ),
        
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(max_length=200)),
                ('date_married', models.DateField()),
                ('priest', models.CharField(max_length=150)),
                ('principal_sponsor', models.CharField(blank=True, max_length=150)),
                ('secondary_sponsor', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='registry.member')),
            ],
        ),
        
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(
                    choices=[
                        ('member', 'Member'),
                        ('officer', 'Officer'),
                        ('president', 'President'),
                        ('vice_president', 'Vice President'),
                        ('secretary', 'Secretary'),
                        ('treasurer', 'Treasurer'),
                        ('auditor', 'Auditor'),
                        ('coordinator', 'Coordinator'),
                        ('advisor', 'Advisor'),
                    ],
                    default='member',
                    max_length=50,
                    verbose_name='Role/Position'
                )),
                ('joined_date', models.DateField(verbose_name='Joined Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='organization_memberships',
                    to='registry.member',
                    verbose_name='Member'
                )),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memberships',
                    to='registry.organization',
                    verbose_name='Organization'
                )),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'ordering': ['-joined_date'],
                'unique_together': {('member', 'organization')},
            },
        ),
        
        migrations.CreateModel(
            name='ParishOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=150, choices=[('parish_priest', 'Parish Priest (Pastor)'), ('parochial_vicar', 'Parochial Vicar / Assistant Priest'), ('ppc_president', 'PPC President / Chairperson'), ('ppc_vice_president', 'PPC Vice President'), ('ppc_secretary', 'PPC Secretary'), ('ppc_treasurer', 'PPC Treasurer'), ('ppc_auditor', 'PPC Auditor'), ('finance_council', 'Parish Finance Council'), ('lector', 'Lector (Readers)'), ('commentator', 'Commentator'), ('altar_servers', 'Altar Servers'), ('choir', 'Choir / Music Ministry'), ('extraordinary_ministers', 'Extraordinary Ministers of Holy Communion'), ('ushers', 'Ushers / Greeters'), ('collectors', 'Collectors'), ('sacristan', 'Sacristan'), ('church_decorators', 'Church Decorators'), ('youth_ministry', 'Youth Ministry'), ('family_ministry', 'Family Ministry'), ('womens_ministry', "Women's Ministry"), ('mens_ministry', "Men's Ministry"), ('catechists', 'Catechists (Religious Teachers)'), ('parish_secretary', 'Parish Secretary'), ('parish_administrator', 'Parish Administrator'), ('social_communications', 'Social Communications Officer'), ('ministry_coordinators', 'Ministry Coordinators'), ('religious_education', 'Religious Education Coordinator')])),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('date_departed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('biography', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='officers/', verbose_name='Profile Image')),
                ('church', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='officers', 
                    to='registry.church', 
                    verbose_name='Assigned Church/Diocese'
                )),
                ('parish', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='officers', 
                    to='registry.parish', 
                    verbose_name='Assigned Parish'
                )),
            ],
            options={
                'verbose_name_plural': 'Parish Officers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        
        migrations.CreateModel(
            name='ParishPriest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ordination_date', models.DateField(blank=True, null=True)),
                ('priest_since', models.DateField(blank=True, null=True)),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('date_departed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('biography', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='priests/', verbose_name='Profile Image')),
                ('church', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='priests', 
                    to='registry.church', 
                    verbose_name='Assigned Church/Diocese'
                )),
                ('parish', models.ForeignKey(
                    blank=True, 
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    related_name='priests', 
                    to='registry.parish', 
                    verbose_name='Assigned Parish'
                )),
            ],
            options={
                'verbose_name_plural': 'Parish Priests',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        
        migrations.CreateModel(
            name='ParishOfficerEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('position', models.CharField(choices=[
                    ('bishop', 'Bishop'),
                    ('priest', 'Priest'),
                    ('deacon', 'Deacon'),
                    ('senior_warden', 'Senior Warden'),
                    ('junior_warden', 'Junior Warden'),
                    ('treasurer', 'Treasurer'),
                    ('secretary', 'Secretary'),
                    ('vestry_member', 'Vestry Member'),
                ], max_length=50, verbose_name='Position')),
                ('date_assigned', models.DateField(verbose_name='Date Assigned')),
                ('date_departed', models.DateField(blank=True, null=True, verbose_name='Date Departed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_officers', to='registry.parish', verbose_name='Parish')),
            ],
            options={
                'verbose_name': 'Parish Officer',
                'verbose_name_plural': 'Parish Officers',
                'ordering': ['position', 'last_name', 'first_name'],
            },
        ),
        
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_pledged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='registry.member')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registry.pledge')),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
        
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pledge_due', 'Pledge Payment Due'), ('pledge_overdue', 'Pledge Payment Overdue')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_pledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.pledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        # Add indexes for better performance
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organization_name_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organization_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['member_id', 'organization_id'], name='membership_member_org_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['role'], name='membership_role_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['is_active'], name='membership_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['joined_date'], name='membership_joined_date_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['name'], name='church_name_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_active'], name='church_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parish',
            index=models.Index(fields=['name'], name='parish_name_idx'),
        ),
        migrations.AddIndex(
            model_name='parish',
            index=models.Index(fields=['church_id'], name='parish_church_idx'),
        ),
        migrations.AddIndex(
            model_name='parish',
            index=models.Index(fields=['parish_type'], name='parish_type_idx'),
        ),
        migrations.AddIndex(
            model_name='parish',
            index=models.Index(fields=['is_active'], name='parish_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parishofficerep',
            index=models.Index(fields=['parish_id'], name='officer_parish_idx'),
        ),
        migrations.AddIndex(
            model_name='parishofficerep',
            index=models.Index(fields=['position'], name='officer_position_idx'),
        ),
        migrations.AddIndex(
            model_name='parishofficerep',
            index=models.Index(fields=['is_active'], name='officer_active_idx'),
        ),
        migrations.AddIndex(
            model_name='parishofficerep',
            index=models.Index(fields=['last_name', 'first_name'], name='officer_name_idx'),
        ),
    ]